### ISSUE TITLE
NX Cannot find project

### ISSUE THREAD

**Issue by griiettner** [lucasvieirasilva/nx-plugins#182]
### Current Behavior

I'm working in a project that will have couple of Python API's, so I was searching for a way to integrate the Python to NX and I found this great plugin, but I'm facing an issue.

I created an app through the command line

```
pnpm exec nx generate @nxlv/python:poetry-project --name=agents --directory=src/apis --moduleName=apis-agents --packageName=apis-agents --no-interactive 


>  NX  Generating @nxlv/python:poetry-project

CREATE src/apis/agents/project.json
CREATE src/apis/agents/README.md
CREATE src/apis/agents/.python-version
CREATE src/apis/agents/apis-agents/__init__.py
CREATE src/apis/agents/apis-agents/hello.py
CREATE src/apis/agents/poetry.toml
CREATE src/apis/agents/pyproject.toml
CREATE src/apis/agents/tests/__init__.py
CREATE src/apis/agents/tests/conftest.py
CREATE src/apis/agents/tests/test_hello.py
CREATE src/apis/agents/.flake8
```

Everything seems to went well, with the exception that the project did not get the name I gave, instead, it changed to 

```
{
  "name": "src-apis-agents",
  "$schema": "../../../node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  ...
}
```

But this is not the reason I'm here. The problem happens when I try to add a package to Poetry by running the command

```
pnpx nx run src-apis-agents:add os                 
.../Library/pnpm/store/v3/tmp/dlx-40561  | +111 +++++++++++
.../Library/pnpm/store/v3/tmp/dlx-40561  | Progress: resolved 120, reused 111, downloaded 0, added 111, done

 >  NX   Cannot find project 'src-apis-agents'

 ERROR  Command failed with exit code 1: nx run src-apis-agents:add os

pnpm: Command failed with exit code 1: nx run src-apis-agents:add os
    at makeError (/Users/griiettner/.cache/node/corepack/pnpm/8.6.11/dist/pnpm.cjs:24890:17)
    at handlePromise (/Users/griiettner/.cache/node/corepack/pnpm/8.6.11/dist/pnpm.cjs:25461:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/griiettner/.cache/node/corepack/pnpm/8.6.11/dist/pnpm.cjs:210334:7)
    at async /Users/griiettner/.cache/node/corepack/pnpm/8.6.11/dist/pnpm.cjs:219737:21
    at async main (/Users/griiettner/.cache/node/corepack/pnpm/8.6.11/dist/pnpm.cjs:219704:34)
    at async runPnpm (/Users/griiettner/.cache/node/corepack/pnpm/8.6.11/dist/pnpm.cjs:219960:5)
    at async /Users/griiettner/.cache/node/corepack/pnpm/8.6.11/dist/pnpm.cjs:219952:7
```

As you can see, it start running and it fails.

For some reason, it does not understand the project exists, but if I go to the `NX Console` in VSCode, I can see the project there

<img width="299" alt="image" src="https://github.com/lucasvieirasilva/nx-plugins/assets/523781/fc377948-4ce0-4cfc-a569-15c674648e8b">

### Expected Behavior

Expect the package to be installed correctly without error

### Steps to Reproduce

1.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

   Node   : 18.12.0
   OS     : darwin-arm64
   pnpm   : 8.6.11
   
   nx (global)    : 17.0.2
   nx             : 17.0.2
   @nx/js         : 17.0.2
   @nx/workspace  : 17.0.2
   @nx/devkit     : 17.0.2
   @nrwl/tao      : 17.0.2
   typescript     : 5.1.6
```
```


### Failure Logs

_No response_

### Additional Information

_No response_

**Comment by lucasvieirasilva** [comment]
Hi @griiettner, nx released version 17 a couple of days ago, I didn't have time to make the proper support for version 17, if you try the same with version 16 it's going to be better.

Thanks

**Comment by lucasvieirasilva** [comment]
@griiettner Nx added `projectNameAndRootFormat` https://nx.dev/nx-api/js/generators/library#projectnameandrootformat property to a bunch of generators and new nx workspaces are being created to use as `as-provided` in the way you are trying to do.

Historically, Nx used to use workspace layout, pretty much folders to store apps and libs, based on that to generate project names, like `apps/apis-agents` folder generates the project name `apis-agents`, and this plugin use the same approach.

however, in newer versions, when you create a project using the generators you choose the folder + project name (`as-provided`).

I'm changing this plugin to also have the `projectNameAndRootFormat` parameter to generator and make `derived` as default for plugin compatibility, but in newer versions I should use the same approach as Nx is using and change the default to `as-provided`

**Comment by griiettner** [comment]
@lucasvieirasilva Thank you very much. I'll try to the updated version and will let you know if things are ok

**Comment by lucasvieirasilva** [comment]
@griiettner I've added some good info to the PR description, and if you have any other questions/issues, please let me know.

Have fun with the plugin!
