### ISSUE TITLE
Failed to process project dependencies with "@nxlv/python". Cannot read properties of undefined (reading 'projects')

### ISSUE THREAD

**Issue by jochemvanweelde** [lucasvieirasilva/nx-plugins#240]
### Current Behavior

I've followed the installation instructions. 
* I installed the python package using npm
* I added "@nxlv/python" to the nx plugin array. 

Now when running any nx command the will result in one of the following responses:

>  NX   Daemon process terminated and closed the connection
>  NX   Failed to process project dependencies with "@nxlv/python".

Running the generator also fails.
When removing the plugin in the pluginarray every command works again and I am also able to run the generator.
However every python nx command won't work due to the plugin not being listed.

### Expected Behavior

After installing the npm package and defining the plugin in the nx plugin array. 
I would be able to run every nx command and generate python poetry applications using this package.

### Steps to Reproduce

1. npm install @nxlv/python --save-dev
2. add to plugins: ```"plugins": [
    "@nxlv/python"
  ]```
3. run `npx nx report`

>  NX   Failed to process project dependencies with "@nxlv/python".

### Nx Report

```shell
#### NO REPORT POSSIBLE WITH PLUGIN LISTED ####

#### REPORT WITHOUT PLUGIN LISTED IN NX ####
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-arm64
   npm    : 10.8.2
   
   nx                 : 16.7.2
   @nx/js             : 16.7.2
   @nx/jest           : 16.7.2
   @nx/linter         : 16.7.2
   @nx/workspace      : 16.7.2
   @nx/cypress        : 16.7.2
   @nx/detox          : 16.7.2
   @nx/devkit         : 18.0.3
   @nx/eslint-plugin  : 16.7.2
   @nx/next           : 16.7.2
   @nx/node           : 16.7.2
   @nx/react          : 16.7.2
   @nrwl/tao          : 16.7.2
   @nx/web            : 16.7.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.3
   ---------------------------------------
   Community plugins:
   @nxlv/python        : 18.1.0
   @nxrocks/nx-flutter : 8.1.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/devkit@18.0.3
     - @nrwl/devkit@18.0.3
   
   To fix this, run `nx migrate nx@18.0.3`

#### REPORT WITHOUT @nxlv/python where everything works ####
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 18.17.0
   OS     : darwin-arm64
   npm    : 10.8.2
   
   nx                 : 16.7.2
   @nx/js             : 16.7.2
   @nx/jest           : 16.7.2
   @nx/linter         : 16.7.2
   @nx/workspace      : 16.7.2
   @nx/cypress        : 16.7.2
   @nx/detox          : 16.7.2
   @nx/devkit         : 18.0.3
   @nx/eslint-plugin  : 16.7.2
   @nx/next           : 16.7.2
   @nx/node           : 16.7.2
   @nx/react          : 16.7.2
   @nrwl/tao          : 16.7.2
   @nx/web            : 16.7.2
   nx-cloud           : 16.0.5
   typescript         : 5.0.3
   ---------------------------------------
   Community plugins:
   @nxrocks/nx-flutter : 8.1.0
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/devkit@18.0.3
     - @nrwl/devkit@18.0.3
   
   To fix this, run `nx migrate nx@18.0.3`
```

### Failure Logs

```shell
[NX Daemon Server] - 2024-08-01T12:14:52.355Z - Started listening on: /var/folders/2f/tcmlznf53nnby773ncm30ph40000gn/T/86827851531eb98f0cc1/d.sock
[NX Daemon Server] - 2024-08-01T12:14:52.356Z - [WATCHER]: Subscribed to changes within: /Users/jochemvanweelde/Repositories/Installation (native)
[NX Daemon Server] - 2024-08-01T12:14:52.364Z - Established a connection. Number of open connections: 1
[NX Daemon Server] - 2024-08-01T12:14:52.364Z - Established a connection. Number of open connections: 2
[NX Daemon Server] - 2024-08-01T12:14:52.365Z - Closed a connection. Number of open connections: 1
[NX Daemon Server] - 2024-08-01T12:14:52.366Z - [REQUEST]: Client Request for Project Graph Received
[NX Daemon Server] - 2024-08-01T12:14:52.490Z - [REQUEST]: Updated file-hasher based on watched changes, recomputing project graph...
[NX Daemon Server] - 2024-08-01T12:14:52.490Z - [REQUEST]: 
[NX Daemon Server] - 2024-08-01T12:14:52.491Z - [REQUEST]: 
[NX Daemon Server] - 2024-08-01T12:14:52.810Z - Error detected when creating a project graph: Failed to process project dependencies with "@nxlv/python".
Cannot read properties of undefined (reading 'projects')
[NX Daemon Server] - 2024-08-01T12:14:52.811Z - [REQUEST]: Responding to the client with an error. Error when preparing serialized project graph. Failed to process project dependencies with "@nxlv/python".
Cannot read properties of undefined (reading 'projects')
TypeError: Failed to process project dependencies with "@nxlv/python".
Cannot read properties of undefined (reading 'projects')
    at Object.createDependencies (/Users/jochemvanweelde/Repositories/Installation/node_modules/@nxlv/python/src/graph/dependency-graph.js:85:35)
    at /Users/jochemvanweelde/Repositories/Installation/node_modules/nx/src/project-graph/build-project-graph.js:154:58
    at Generator.next (<anonymous>)
    at fulfilled (/Users/jochemvanweelde/Repositories/Installation/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[NX Daemon Server] - 2024-08-01T12:14:52.811Z - Done responding to the client null
```

### Additional Information

It looks like that context is undefined in the function createDependencies in `./graph/dependency-graph.js`

when changing this function from:
```js
const createDependencies = (_, context) => {
    const result = [];
    for (const project in context.projects) {
        const deps = (0, exports.getDependencies)(project, context.projects, process.cwd());
        deps.forEach((dep) => {
            result.push({
                source: project,
                target: dep.name,
                type: devkit_1.DependencyType.implicit,
            });
        });
    }
    return result;
};
```
to
```js
const createDependencies = (_, context) => {
    const result = [];
    for (const project in context?.projects) {
        const deps = (0, exports.getDependencies)(project, context.projects, process.cwd());
        deps.forEach((dep) => {
            result.push({
                source: project,
                target: dep.name,
                type: devkit_1.DependencyType.implicit,
            });
        });
    }
    return result;
};
```
(note the ? after context) everything seems to work perfectly after changing this manually. When running `npx nx show projects` all projects including python poetry applications are listed. Every command works, also tests, linting etc.

**Comment by lucasvieirasilva** [comment]
Hi @jochemvanweelde, I think the reason is the `@nxlv/python` version you are using, can you install the https://www.npmjs.com/package/@nxlv/python/v/16.3.1 instead?

The `@nxlv/python` usually follows the Nx major versions to make sure they are compatible, and I've noticed your Nx workspace is 16.x

**Comment by jochemvanweelde** [comment]
Hi @lucasvieirasilva,
Thanks for the quick response! 
It seems this was the solution, I should've thought of that 😅

I needed to change some dependencies since @nx/devkit was incompatible with nx python v16. 
Nx report already warned me about this.
This required me to also downgrade the nx flutter plugin to match with nx 16. 

Now it seems everything works as expected for this package. Thanks for the help!
